<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.176">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matt Dray">
<meta name="dcterms.date" content="2019-12-08">

<title>rostrum.blog - {altcheckr}: check image alt text from R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/logo-black-trans.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "keyboard-shortcut": [
    null
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/logo-green-trans.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">rostrum.blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target=""><i class="bi bi-question-circle-fill" role="img">
</i> 
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss-fill" role="img" aria-label="RSS feed">
</i> 
 <span class="menu-text">RSS</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/matt-dray/rostrum-blog-2" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub source code">
</i> 
 <span class="menu-text">Source</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">{altcheckr}: check image alt text from R</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">accessibility</div>
                <div class="quarto-category">hunspell</div>
                <div class="quarto-category">polite</div>
                <div class="quarto-category">r</div>
                <div class="quarto-category">rvest</div>
                <div class="quarto-category">scrape</div>
                <div class="quarto-category">xml2</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p><a href="https://www.matt-dray.com">Matt Dray</a> </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 8, 2019</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">tl;dr</a></li>
  <li><a href="#accessibility" id="toc-accessibility" class="nav-link" data-scroll-target="#accessibility">Accessibility</a>
  <ul class="collapse">
  <li><a href="#screen-readers" id="toc-screen-readers" class="nav-link" data-scroll-target="#screen-readers">Screen readers</a></li>
  <li><a href="#when-and-what-to-write" id="toc-when-and-what-to-write" class="nav-link" data-scroll-target="#when-and-what-to-write">When and what to write</a></li>
  </ul></li>
  <li><a href="#chancellor-of-the-altcheckr" id="toc-chancellor-of-the-altcheckr" class="nav-link" data-scroll-target="#chancellor-of-the-altcheckr">Chancellor of the {altcheckr}</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#interpret-the-data" id="toc-interpret-the-data" class="nav-link" data-scroll-target="#interpret-the-data">Interpret the data</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps">Next steps</a></li>
  </ul></li>
  
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><img src="resources/altcheckr_hex.png" class="img-fluid" style="width:30.0%" alt="Hex sticker for altchecker, with the package name, a checkmark and the URL matt-dray.github.io/altcheckr."></p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">tl;dr</h2>
<p>I’ve made a small concept R package called <a href="https://matt-dray.github.io/altcheckr/">{altcheckr}</a> that checks the accessibility of images on web pages. It has functions that (1) scrape attributes from HTML <img> elements on a web page and (2) apply simple rules to indicate the suitability of the alt text provided.</p>
</section>
<section id="accessibility" class="level2">
<h2 class="anchored" data-anchor-id="accessibility">Accessibility</h2>
<p>A web site is <a href="https://en.wikipedia.org/wiki/Accessibility">accessible</a> if everyone can engage with its content. There are <a href="https://www.w3.org/TR/WCAG20/">Web Content Accessibility Guidelines</a> (WCAG) from the <a href="https://www.w3.org/">World Wide Web Consortium</a> (W3C) to help achieve this and <a href="https://www.w3.org/WAI/ER/tools/">many (often free) tools for checking accessibility issues</a>. It’s pressing because <a href="https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps">the law in the UK has recently changed</a> to ensure that all public sector websites publish an accessibility statement.</p>
<p>One obvious target for improvement is accessibility of images.</p>
<section id="screen-readers" class="level3">
<h3 class="anchored" data-anchor-id="screen-readers">Screen readers</h3>
<p><a href="https://en.wikipedia.org/wiki/Screen_reader">Screen readers</a> are a technology that parse text on a web page and output it as speech audio. They’re particularly helpful for blind and partially-sighted people.</p>
<p>Images are declared in the HTML code of a website with <a href="https://www.w3schools.com/tags/tag_img.asp">the <code>&lt;img&gt;</code> element</a>. Like other HTML tags, it can have many ‘attributes’: the source of the image (where the image is actually hosted), the height and width of the image, and so on.</p>
<p>The ‘alt’ attribute provides alternative text that describes the image. This text won’t be visible to people visiting the page (unless you right-click and ‘inspect’ the HTML for the page), but will be picked up screen readers.</p>
</section>
<section id="when-and-what-to-write" class="level3">
<h3 class="anchored" data-anchor-id="when-and-what-to-write">When and what to write</h3>
<p>What should you actually write as alternative text for an image? It depends on the type of image. To summarise <a href="https://www.w3.org/WAI/tutorials/images/decision-tree/">the alt decision tree by W3C</a>:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Image type</th>
<th style="text-align: left;">Alt text suggestion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Informative</td>
<td style="text-align: left;">A short, complete, descriptive sentence.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Decorative</td>
<td style="text-align: left;">None required (<code>alt = ""</code>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Functional</td>
<td style="text-align: left;">A short description of the purpose served (if it’s a button, for example).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contains text</td>
<td style="text-align: left;">Text should be repeated unless in the main body text.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Complex</td>
<td style="text-align: left;">Describe in the main body text or provide a <code>longdesc</code> attribute that links to a page containing a longer description.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="chancellor-of-the-altcheckr" class="level2">
<h2 class="anchored" data-anchor-id="chancellor-of-the-altcheckr">Chancellor of the {altcheckr}</h2>
<p>I’ve been writing different sorts of R packages recently (see posts on <a href="https://www.rostrum.blog/2019/11/01/usethis/">{usethis}</a>, <a href="https://www.rostrum.blog/2019/02/27/hadley-number/">{kevinbacran}</a>, <a href="https://www.rostrum.blog/2019/10/22/blogsnip/">{blogsnip}</a> and <a href="https://www.rostrum.blog/2019/05/24/xaringan-template/">{gdstheme}</a>) and I’ve have also <a href="https://www.rostrum.blog/2018/05/12/accessibility-workshop-at-sprint18/">written briefly on accessibility</a> and <a href="https://www.rostrum.blog/2018/07/12/accessible-accessibility/">some related tools</a>.</p>
<p>To this end, I’ve written a small R package called {altcheckr} to help assess alt text programmatically. Go to <a href="https://github.com/matt-dray/altcheckr">the source on GitHub</a> or see <a href="https://matt-dray.github.io/altcheckr/">the site</a> built with {pkgdown}.</p>
<p>Note that {altcheckr} isn’t intended to provide a definitive evaluation of alt text. It uses simple heuristics and doesn’t contain everything that could be checked. I’m not an expert and the package isn’t user tested.</p>
<p>It has only two functions for now:</p>
<ul>
<li><code>alt_get()</code> scrapes the web page at a URL provided by the user and outputs a data frame where each row is an image and each column is an HTML attribute</li>
<li><code>alt_check()</code> takes the output from <code>alt_get()</code> and adds a series of columns that assess features of the alt text, like its length</li>
</ul>
<p>It also contains the <code>example_get</code> data set, which is a dummy output from <code>alt_get()</code> to be used to experiment with <code>alt_check()</code>.</p>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>Let’s walk through how you can get the package, fetch alt text from a webpage and then assess it.</p>
<section id="install" class="level4">
<h4 class="anchored" data-anchor-id="install">Install</h4>
<p>You can get the package from GitHub with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"remotes"</span>)  <span class="co"># if not yet installed</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install_github</span>(<span class="st">"matt-dray/altcheckr"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(altcheckr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="alt_get" class="level4">
<h4 class="anchored" data-anchor-id="alt_get">alt_get()</h4>
<p>The <code>alt_get()</code> function makes use of {polite}, {xml2} and {rvest} to scrape a web page and isolate attributes from its <code>&lt;img&gt;</code> elements. If {polite} determines that it’s okay to scrape, <code>alt_get()</code> returns a tibble after some {purrr} wrangling, where each row is an image. You can choose to retain all scraped attributes as columns, or it defaults to returning just <code>src</code> and <code>alt</code> (<code>longdesc</code> too if it exists).</p>
<p>We’ll use the <a href="https://www.bbc.co.uk/news">BBC News</a> home page as our example. A popular site with constantly-updating content that you would expect to have good alt text.</p>
<div class="figure">
<img src="resources/bbc-news.png" alt="The sports section of the BBC News home page showing several images of athletes." width="700">
<p class="caption">
BBC News sports section. How would you describe these images in alt text?
</p>
</div>
<p>Pass the web page’s URL to <code>alt_get()</code> to return a tibble where each row is an image from the page and there are columns for the image source (<code>src</code>) and alt text (<code>alt</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bbc_get <span class="ot">&lt;-</span> <span class="fu">alt_get</span>(<span class="st">"https://www.bbc.co.uk/news"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(bbc_get)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Classes 'tbl_df', 'tbl' and 'data.frame':    105 obs. of  2 variables:
$ src: chr  "https://a1.api.bbc.co.uk/hit.xiti?&amp;col=1&amp;from=p&amp;ptag=js&amp;s=598253&amp;p=unknown&amp;x1=[urn:bbc:cps:b5c53243-a695-e059-e"| __truncated__ "https://ichef.bbci.co.uk/news/320/cpsprodpb/14E0/production/_98244350_pa.jpg" "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" ...
$ alt: chr  "" "The Irish border" "Airman Mohammad Sameh Haitham (left) and ensign Joshua Kaleb Watson" "Crowds" ...</code></pre>
<p>A whopping 105 images! Let’s take a look at the first few alt text entries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bbc_get<span class="sc">$</span>alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>[1] ""                                                                                            
[2] "The Irish border"                                                                            
[3] "Airman Mohammad Sameh Haitham (left) and ensign Joshua Kaleb Watson"                         
[4] "Crowds"                                                                                      
[5] "Wellingborough Road, Rushden"                                                                
[6] "Juice Wrld, real name Jarad Anthony Higgins, was considered to be a rising star of rap music"</code></pre>
<p>Some of these seem quite short and aren’t particularly descriptive; even without having seen the images that they relate to. Let’s do a simple assessment of the alt text using the <code>alt_check()</code> function to provide a bit more information.</p>
</section>
<section id="alt_check" class="level4">
<h4 class="anchored" data-anchor-id="alt_check">alt_check()</h4>
<p>The <code>alt_check()</code> function takes the output from <code>alt_get()</code> and generates some new variables based on the alt text.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bbc_check <span class="ot">&lt;-</span> <span class="fu">alt_check</span>(bbc_get)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">packagelibrary</span>(dplyr)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bbc_check)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>Observations: 105
Variables: 10
$ src            &lt;chr&gt; "https://a1.api.bbc.co.uk/hit.xiti?&amp;col=1&amp;from=p&amp;…
$ alt            &lt;chr&gt; "", "The Irish border", "Airman Mohammad Sameh Ha…
$ alt_exists     &lt;chr&gt; "Empty", "Exists", "Exists", "Exists", "Exists", …
$ nchar_count    &lt;int&gt; NA, 16, 67, 6, 28, 92, 37, 16, 14, 38, 4, 10, 26,…
$ nchar_assess   &lt;chr&gt; NA, "Short", "OK", "Short", "OK", "OK", "OK", "Sh…
$ file_ext       &lt;lgl&gt; NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…
$ self_evident   &lt;lgl&gt; NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…
$ terminal_punct &lt;lgl&gt; NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…
$ spellcheck     &lt;list&gt; [&lt;&gt;, &lt;&gt;, &lt;"Sameh", "Haitham", "Kaleb"&gt;, &lt;&gt;, &lt;"We…
$ not_basic      &lt;list&gt; [&lt;&gt;, &lt;"irish", "border"&gt;, &lt;"airman", "mohammad",…</code></pre>
<p>You can see a number of new columns in addition to <code>src</code> and <code>alt</code> that were output from <code>alt_get()</code>. These are as follows, with reasoning:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Column name</th>
<th style="text-align: left;">What</th>
<th style="text-align: left;">Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>alt_exists</code></td>
<td style="text-align: left;">Has alt text been provided?</td>
<td style="text-align: left;">A lack of alt text could be a problem, though it’s acceptable if the image is decorative.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>nchar_count</code></td>
<td style="text-align: left;">Number of characters in the alt text.</td>
<td style="text-align: left;">Used in <code>nchar_assess</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>nchar_assess</code></td>
<td style="text-align: left;">Categorical. Whether the alt text is ‘short’ (defaults to 20 characters), ‘long’ (125) or ‘okay’.</td>
<td style="text-align: left;">Short alt text might not describe the image well, but is acceptable for things like buttons, for example. Long alt text might be too verbose and should probably put in a <code>longdesc</code> attribute.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>file_ext</code></td>
<td style="text-align: left;">Logical. Does the alt text appear to be a file name?</td>
<td style="text-align: left;">Alt text shouldn’t contain a file name.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>self_evident</code></td>
<td style="text-align: left;">Logical. Does the alt text contain redundant phrases?</td>
<td style="text-align: left;">It doesn’t need to say ‘a picture showing…’ or similar.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>terminal_punct</code></td>
<td style="text-align: left;">Logical. Does the alt text end in terminal punctuation?</td>
<td style="text-align: left;">The alt text should end in a sentence terminator, like a full stop. This means the screen reader will parse it as a proper sentence.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>spellcheck</code></td>
<td style="text-align: left;">A listcol of character vectors detailing misspelled words according to <code>hunspell</code> from the {hunspell} package.</td>
<td style="text-align: left;">Errors in spelling may result in the screen reader misreading a word.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>not_basic</code></td>
<td style="text-align: left;">A listcol of character vectors that aren’t in <a href="https://en.wikipedia.org/wiki/Basic_English">Charles Kay Ogden’s Basic English</a> list.</td>
<td style="text-align: left;">Text is more accessible in general if it uses simple English.</td>
</tr>
</tbody>
</table>
<p><a href="https://github.com/matt-dray/altcheckr/issues">I’d like to hear your thoughts</a> on these variables and if you’d like to suggest others. <a href="https://github.com/matt-dray/altcheckr">Contributions to the GitHub repository</a> are very welcome.</p>
</section>
</section>
<section id="interpret-the-data" class="level3">
<h3 class="anchored" data-anchor-id="interpret-the-data">Interpret the data</h3>
<p>You can take the output from <code>alt_check()</code> and investigate further. Here’s two very simple and plainly-presented examples.</p>
<p>Let’s look first at the length of the alt text. This histogram shows the distribution of character counts coloured by the <code>nchar_assess</code> variable, giving different colours to alt text that’s under 20 (‘short’) or over 125 (‘long’) characters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>bbc_check <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(nchar_count)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">fill =</span> nchar_assess),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">5</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of character lengths in image alt text"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"BBC News home page,"</span>, <span class="fu">Sys.Date</span>()),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: https://www.bbc.co.uk/news via the {altcheckr} package"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Character count"</span>, <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="resources/unnamed-chunk-8-1.png" class="img-fluid" style="width:100.0%" alt="Histogram of alt text length in characters, spread from 0 to 100 on the x-axis. Most common if about 20."></p>
<p>So you can there’s see a lot of short alt text that might need looking at if the images are meant to be informative. For example, here’s the 10 shortest:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bbc_check <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nchar_count <span class="sc">&lt;</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(nchar_count) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(alt, nchar_count) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code># A tibble: 10 x 2
alt          nchar_count
&lt;chr&gt;              &lt;int&gt;
1 Fred                   4
2 Santa                  5
3 Crowds                 6
4 Celeste                7
5 Pork pie               8
6 Liam Payne            10
7 quiz promo            10
8 Tie fighter           11
9 Jamie Vardy           11
10 Emma Spencer          12</code></pre>
<p>Next: how does the alt text of images make use of terminal punctuation (period, exclamation point or question mark)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bbc_check <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(terminal_punct) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span>  <span class="co"># count within the variable</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> terminal_punct, <span class="at">y =</span> Count)) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Existence of terminal punctuation (., !, ?) in alt text"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"BBC News home page,"</span>, <span class="fu">Sys.Date</span>()),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Source: https://www.bbc.co.uk/news via the {altcheckr} package"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Terminal punctuation exists"</span>, </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="resources/unnamed-chunk-9-1.png" class="img-fluid" style="width:100.0%" alt="Bar chart showing presence of terminal punctuation in alt text. About 100 alt texts did not have terminal punctuation and only a couple did."></p>
<p>So most of the alt text does not end in terminal punctuation (<code>FALSE</code>), which is a bit disappointing. This means a screen reader might not fully parse the image as a complete sentence.</p>
<p>Note that the findings here aren’t definitive and each case would need to be looked further into. However, these very shallow analyses imply that there are some improvements to make.</p>
</section>
<section id="next-steps" class="level3">
<h3 class="anchored" data-anchor-id="next-steps">Next steps</h3>
<p>There’s a number of <code>alt_check()</code> additions that could be developed. For example:</p>
<ul>
<li>optical character recognition (OCR) to decide whether an image has text in it, and to possibly extract it</li>
<li>guess the type of image based on its attributes and derived variables (a functional image might have relatively small height and width attributes, for example)</li>
<li>assess the text in the link provided by the <code>longdesc</code> attribute, if it exists</li>
<li>detect ‘link stuffing’, where alt text is filed with keywords for purposes of search engine optimisation</li>
</ul>
<p>And of course: better unit testing and test coverage, simplifying the dependencies (there’s lots) and making the code more efficient. <a href="https://github.com/matt-dray/altcheckr/issues">Tell me about other things that can be improved</a>.</p>
<p>Ultimately, my call to action for R users is to explore the wealth of materials for package development<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and for everyone to take a moment to think about your users and the accessibility of whatever you’re producing.</p>
</section>
</section>



<div id="quarto-appendix" class="default"><section id="environment" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Environment</h2><div class="quarto-appendix-contents">

<details>
<summary>
Session info
</summary>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Last rendered: 2023-07-23 11:06:21 BST</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] altcheckr_0.1.0

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.2 compiler_4.3.1    fastmap_1.1.1     cli_3.6.1        
 [5] tools_4.3.1       htmltools_0.5.5   rstudioapi_0.15.0 yaml_2.3.7       
 [9] rmarkdown_2.23    knitr_1.43.1      jsonlite_1.8.7    xfun_0.39        
[13] digest_0.6.33     rlang_1.1.1       evaluate_0.21    </code></pre>
</div>
</div>
</details>


</div></section><aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Particularly from <a href="https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/">Emil Hvitfeldt</a>, <a href="https://kbroman.org/pkg_primer/">Karl Broman</a> and <a href="http://r-pkgs.had.co.nz/">Hadley Wickham</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</aside><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div id="quarto-reuse" class="quarto-appendix-contents"><div>CC BY-NC-SA 4.0</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    if (id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        return container.innerHTML
      } else {
        return note.innerHTML;
      }
    } else {
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      try { hash = new URL(url).hash; } catch {}
      const id = hash.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note !== null) {
        try {
          const html = processXRef(id, note);
          instance.setContent(html);
        } finally {
          instance.enable();
          instance.show();
        }
      } else {
        // See if we can fetch this
        fetch(url.split('#')[0])
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.getElementById(id);
          if (note !== null) {
            const html = processXRef(id, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>