# More at: https://quarto.org/docs/reference/projects/websites.html
# Dropdown menu idea borrowed from jhelvy.com

project:
  type: website

website:
  title: rostrum.blog (test)
  site-url: https://whimsical-wisp-30974e.netlify.app/
  repo-url: https://github.com/matt-dray/rostrum-blog-2
  favicon: images/logo-black-trans.png
  description: Japes with R
  navbar:
    background: black
    foreground: "#00FF00"
    logo: images/logo-green-trans.png
    right:
      - menu:
        - icon: question-circle-fill
          href: about.qmd
        - icon: rss-fill
          aria-label: RSS feed
          text: RSS
          href: index.xml
        - icon: github
          aria-label: GitHub source code
          text: Source
          href: https://github.com/matt-dray/rostrum-blog-2
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: styles.scss
    css: styles.css
