# More at: https://quarto.org/docs/reference/projects/websites.html

project:
  type: website

website:
  title: rostrum.blog
  site-url: https://www.rostrum.blog
  favicon: images/logo-green-trans.png
  description: Japes with R
  open-graph: true
  twitter-card:
    creator: "@mattdray"
  navbar:
    background: black
    foreground: "#00FF00"
    logo: images/logo-green-trans.png
    right:
      - icon: question-circle-fill
        text: About
        href: about.qmd
      - icon: rss-fill
        aria-label: RSS feed
        text: RSS
        href: index.xml
      - icon: github
        aria-label: GitHub source code
        text: Source
        href: https://github.com/matt-dray/rostrum-blog-2
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: styles.scss
    css: styles.css
