{
  "hash": "f16313da1382ee39430d00e6ff0ef0a1",
  "result": {
    "markdown": "---\ntitle: '{altcheckr}: check image alt text from R'\ndate: 2019-12-08\nslug: altcheckr\ncategories:\n  - accessibility\n  - hunspell\n  - polite\n  - r\n  - rvest\n  - scrape\n  - xml2\n---\n\n::: {.cell}\n\n:::\n\n\n![](resources/altcheckr_hex.png){fig-alt=\"Hex sticker for altchecker, with the package name, a checkmark and the URL matt-dray.github.io/altcheckr.\" width=\"30%\"}\n\n## tl;dr\n\nI've made a small concept R package called [{altcheckr}](https://matt-dray.github.io/altcheckr/) that checks the accessibility of images on web pages. It has functions that (1) scrape attributes from HTML <img> elements on a web page and (2) apply simple rules to indicate the suitability of the alt text provided.\n\n## Accessibility\n\nA web site is [accessible](https://en.wikipedia.org/wiki/Accessibility)  if everyone can engage with its content. There are [Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG20/) (WCAG) from the [World Wide Web Consortium](https://www.w3.org/) (W3C) to help achieve this and [many (often free) tools for checking accessibility issues](https://www.w3.org/WAI/ER/tools/). It's pressing because [the law in the UK has recently changed](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps) to ensure that all public sector websites publish an accessibility statement.\n\nOne obvious target for improvement is accessibility of images.\n\n### Screen readers\n\n[Screen readers](https://en.wikipedia.org/wiki/Screen_reader) are a technology that parse text on a web page and output it as speech audio. They're particularly helpful for blind and partially-sighted people.\n\nImages are declared in the HTML code of a website with [the `<img>` element](https://www.w3schools.com/tags/tag_img.asp). Like other HTML tags, it can have many 'attributes': the source of the image (where the image is actually hosted), the height and width of the image, and so on.\n\nThe 'alt' attribute provides alternative text that describes the image. This text won't be visible to people visiting the page (unless you right-click and 'inspect' the HTML for the page), but will be picked up screen readers.\n\n### When and what to write\n\nWhat should you actually write as alternative text for an image? It depends on the type of image. To summarise [the alt decision tree by W3C](https://www.w3.org/WAI/tutorials/images/decision-tree/):\n\n| Image type | Alt text suggestion |\n| :---- | :---- |\n| Informative | A short, complete, descriptive sentence. |\n| Decorative | None required (`alt = \"\"`). |\n| Functional | A short description of the purpose served (if it's a button, for example). |\n| Contains text | Text should be repeated unless in the main body text. |\n| Complex | Describe in the main body text or provide a `longdesc` attribute that links to a page containing a longer description. |\n\n## Chancellor of the {altcheckr}\n\nI've been writing different sorts of R packages recently\n(see posts on [{usethis}](https://www.rostrum.blog/2019/11/01/usethis/), [{kevinbacran}](https://www.rostrum.blog/2019/02/27/hadley-number/), [{blogsnip}](https://www.rostrum.blog/2019/10/22/blogsnip/) and [{gdstheme}](https://www.rostrum.blog/2019/05/24/xaringan-template/)) and I've have also [written briefly on accessibility](https://www.rostrum.blog/2018/05/12/accessibility-workshop-at-sprint18/) and [some related tools](https://www.rostrum.blog/2018/07/12/accessible-accessibility/).\n\nTo this end, I've written a small R package called {altcheckr} to help assess alt text programmatically. Go to [the source on GitHub](https://github.com/matt-dray/altcheckr) or see [the site](https://matt-dray.github.io/altcheckr/) built with {pkgdown}.\n\nNote that {altcheckr} isn't intended to provide a definitive evaluation of alt text. It uses simple heuristics and doesn't contain everything that could be checked. I'm not an expert and the package isn't user tested.\n\nIt has only two functions for now:\n\n* `alt_get()` scrapes the web page at a URL provided by the user and outputs a data frame where each row is an image and each column is an HTML attribute\n* `alt_check()` takes the output from `alt_get()` and adds a series of columns that assess features of the alt text, like its length\n\nIt also contains the `example_get` data set, which is a dummy output from `alt_get()` to be used to experiment with `alt_check()`.\n\n### Example\n\nLet's walk through how you can get the package, fetch alt text from a webpage and then assess it.\n\n#### Install\n\nYou can get the package from GitHub with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"remotes\")  # if not yet installed\ninstall_github(\"matt-dray/altcheckr\")\nlibrary(altcheckr)\n```\n:::\n\n\n#### alt_get()\n\nThe `alt_get()` function makes use of {polite}, {xml2} and {rvest} to scrape a web page and isolate attributes from its `<img>` elements. If {polite} determines that it's okay to scrape, `alt_get()` returns a tibble after some {purrr} wrangling, where each row is an image. You can choose to retain all scraped attributes as columns, or it defaults to returning just `src` and `alt` (`longdesc` too if it exists).\n\nWe'll use the [BBC News](https://www.bbc.co.uk/news) home page as our example. A popular site with constantly-updating content that you would expect to have good alt text.\n\n<div class=\"figure\">\n<img src=\"resources/bbc-news.png\" alt=\"The sports section of the BBC News home page showing several images of athletes.\" width=700 />\n<p class=\"caption\">BBC News sports section. How would you describe these images in alt text?</p>\n</div>\n\nPass the web page's URL to `alt_get()` to return a tibble where each row is an image from the page and there are columns for the image source (`src`) and alt text  (`alt`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbbc_get <- alt_get(\"https://www.bbc.co.uk/news\")\nstr(bbc_get)\n```\n:::\n\n```\nClasses 'tbl_df', 'tbl' and 'data.frame':    105 obs. of  2 variables:\n$ src: chr  \"https://a1.api.bbc.co.uk/hit.xiti?&col=1&from=p&ptag=js&s=598253&p=unknown&x1=[urn:bbc:cps:b5c53243-a695-e059-e\"| __truncated__ \"https://ichef.bbci.co.uk/news/320/cpsprodpb/14E0/production/_98244350_pa.jpg\" \"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" \"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" ...\n$ alt: chr  \"\" \"The Irish border\" \"Airman Mohammad Sameh Haitham (left) and ensign Joshua Kaleb Watson\" \"Crowds\" ...\n```\n\nA whopping 105 images! Let's take a look at the first few alt text entries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(bbc_get$alt)\n```\n:::\n\n```\n[1] \"\"                                                                                            \n[2] \"The Irish border\"                                                                            \n[3] \"Airman Mohammad Sameh Haitham (left) and ensign Joshua Kaleb Watson\"                         \n[4] \"Crowds\"                                                                                      \n[5] \"Wellingborough Road, Rushden\"                                                                \n[6] \"Juice Wrld, real name Jarad Anthony Higgins, was considered to be a rising star of rap music\"\n```\nSome of these seem quite short and aren't particularly descriptive; even without having seen the images that they relate to. Let's do a simple assessment of the alt text using the `alt_check()` function to provide a bit more information.\n\n#### alt_check()\n\nThe `alt_check()` function takes the output from `alt_get()` and generates some new variables based on the alt text. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbbc_check <- alt_check(bbc_get)\n\npackagelibrary(dplyr)\nglimpse(bbc_check)\n```\n:::\n\n```\nObservations: 105\nVariables: 10\n$ src            <chr> \"https://a1.api.bbc.co.uk/hit.xiti?&col=1&from=p&…\n$ alt            <chr> \"\", \"The Irish border\", \"Airman Mohammad Sameh Ha…\n$ alt_exists     <chr> \"Empty\", \"Exists\", \"Exists\", \"Exists\", \"Exists\", …\n$ nchar_count    <int> NA, 16, 67, 6, 28, 92, 37, 16, 14, 38, 4, 10, 26,…\n$ nchar_assess   <chr> NA, \"Short\", \"OK\", \"Short\", \"OK\", \"OK\", \"OK\", \"Sh…\n$ file_ext       <lgl> NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…\n$ self_evident   <lgl> NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…\n$ terminal_punct <lgl> NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…\n$ spellcheck     <list> [<>, <>, <\"Sameh\", \"Haitham\", \"Kaleb\">, <>, <\"We…\n$ not_basic      <list> [<>, <\"irish\", \"border\">, <\"airman\", \"mohammad\",…\n```\n\nYou can see a number of new columns in addition to `src` and `alt` that were output from `alt_get()`. These are as follows, with reasoning:\n\n| Column name | What | Why |\n| :----- | :----- | :----- |\n| `alt_exists` | Has alt text been provided? | A lack of alt text could be a problem, though it's acceptable if the image is decorative. |\n| `nchar_count` | Number of characters in the alt text. | Used in `nchar_assess` |\n| `nchar_assess` | Categorical. Whether the alt text is 'short' (defaults to 20 characters), 'long' (125) or 'okay'. | Short alt text might not describe the image well, but is acceptable for things like buttons, for example. Long alt text might be too verbose and should probably put in a `longdesc` attribute. |\n| `file_ext` | Logical. Does the alt text appear to be a file name? | Alt text shouldn't contain a file name. |\n| `self_evident` | Logical. Does the alt text contain redundant phrases? | It doesn't need to say 'a picture showing...' or similar. |\n| `terminal_punct` | Logical. Does the alt text end in terminal punctuation? | The alt text should end in a sentence terminator, like a full stop. This means the screen reader will parse it as a proper sentence. |\n| `spellcheck` | A listcol of character vectors detailing misspelled words according to `hunspell` from the {hunspell} package. | Errors in spelling may result in the screen reader misreading a word. |\n| `not_basic` | A listcol of character vectors that aren't in [Charles Kay Ogden's Basic English](https://en.wikipedia.org/wiki/Basic_English) list.  | Text is more accessible in general if it uses simple English. |\n\n[I'd like to hear your thoughts](https://github.com/matt-dray/altcheckr/issues) on these variables and if you'd like to suggest others. [Contributions to the GitHub repository](https://github.com/matt-dray/altcheckr) are very welcome.\n\n### Interpret the data\n\nYou can take the output from `alt_check()` and investigate further. Here's two very simple and plainly-presented examples.\n\nLet's look first at the length of the alt text. This histogram shows the distribution of character counts coloured by the `nchar_assess` variable, giving different colours to alt text that's under 20 ('short') or over 125 ('long') characters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nbbc_check %>%\n  ggplot(aes(nchar_count)) +\n  geom_histogram(\n    aes(fill = nchar_assess),\n    binwidth = 5, \n    na.rm = TRUE\n  ) +\n  labs(\n    title = \"Distribution of character lengths in image alt text\",\n    subtitle = paste(\"BBC News home page,\", Sys.Date()),\n    caption = \"Source: https://www.bbc.co.uk/news via the {altcheckr} package\",\n    x = \"Character count\", y = \"Count\"\n  ) + theme_classic() + theme(legend.title = element_blank())\n```\n:::\n\n![](resources/unnamed-chunk-8-1.png){fig-alt=\"Histogram of alt text length in characters, spread from 0 to 100 on the x-axis. Most common if about 20.\" width=\"100%\"}\n\nSo you can there's see a lot of short alt text that might need looking at if the images are meant to be informative. For example, here's the 10 shortest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbbc_check %>%\n  filter(nchar_count < 20) %>%\n  arrange(nchar_count) %>%\n  distinct(alt, nchar_count) %>%\n  slice(1:10)\n```\n:::\n\n```\n# A tibble: 10 x 2\nalt          nchar_count\n<chr>              <int>\n1 Fred                   4\n2 Santa                  5\n3 Crowds                 6\n4 Celeste                7\n5 Pork pie               8\n6 Liam Payne            10\n7 quiz promo            10\n8 Tie fighter           11\n9 Jamie Vardy           11\n10 Emma Spencer          12\n```\n\nNext: how does the alt text of images make use of terminal punctuation (period, exclamation point or question mark)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbbc_check %>%\n  group_by(terminal_punct) %>%\n  summarise(Count = n()) %>%  # count within the variable\n  ggplot(aes(x = terminal_punct, y = Count)) +\n  geom_bar(stat = \"identity\") +\n  labs(\n    title = \"Existence of terminal punctuation (., !, ?) in alt text\",\n    subtitle = paste(\"BBC News home page,\", Sys.Date()),\n    caption = \"Source: https://www.bbc.co.uk/news via the {altcheckr} package\",\n    x = \"Terminal punctuation exists\", \n    y = \"Count\"\n  ) + theme_classic() +\n  coord_flip() + \n  theme_classic()\n```\n:::\n\n![](resources/unnamed-chunk-9-1.png){fig-alt=\"Bar chart showing presence of terminal punctuation in alt text. About 100 alt texts did not have terminal punctuation and only a couple did.\" width=\"100%\"}\n\nSo most of the alt text does not end in terminal punctuation (`FALSE`), which is a bit disappointing. This means a screen reader might not fully parse the image as a complete sentence.\n\nNote that the findings here aren't definitive and each case would need to be looked further into. However, these very shallow analyses imply that there are some improvements to make.\n\n### Next steps\n\nThere's a number of `alt_check()` additions that could be developed. For example:\n\n* optical character recognition (OCR) to decide whether an image has text in it, and to possibly extract it\n* guess the type of image based on its attributes and derived variables (a functional image might have relatively small height and width attributes, for example)\n* assess the text in the link provided by the `longdesc` attribute, if it exists\n* detect 'link stuffing', where alt text is filed with keywords for purposes of search engine optimisation\n\nAnd of course: better unit testing and test coverage, simplifying the dependencies (there's lots) and making the code more efficient. [Tell me about other things that can be improved](https://github.com/matt-dray/altcheckr/issues).\n\nUltimately, my call to action for R users is to explore the wealth of materials for package development[^pkg_devel] and for everyone to take a moment to think about your users and the accessibility of whatever you're producing. \n\n## Environment {.appendix}\n\n<details><summary>Session info</summary>\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nLast rendered: 2023-07-23 11:06:21 BST\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.1 (2023-06-16)\nPlatform: aarch64-apple-darwin20 (64-bit)\nRunning under: macOS Ventura 13.2.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/London\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] altcheckr_0.1.0\n\nloaded via a namespace (and not attached):\n [1] htmlwidgets_1.6.2 compiler_4.3.1    fastmap_1.1.1     cli_3.6.1        \n [5] tools_4.3.1       htmltools_0.5.5   rstudioapi_0.15.0 yaml_2.3.7       \n [9] rmarkdown_2.23    knitr_1.43.1      jsonlite_1.8.7    xfun_0.39        \n[13] digest_0.6.33     rlang_1.1.1       evaluate_0.21    \n```\n:::\n:::\n\n</details>\n\n[^pkg_devel]: Particularly from [Emil Hvitfeldt](https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/), [Karl Broman](https://kbroman.org/pkg_primer/) and [Hadley Wickham](http://r-pkgs.had.co.nz/).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}